core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.admin import shop_admin

from shop.views import (home, post_view, product_detail_view,
                        test2, http_response, redirect_view)
from crm.views import search_view

urlpatterns = [
path('', home),
path('shop/', include('shop.urls', namespace='shop')),
    path('auth/', include('django.contrib.auth.urls')),
    path('test2/', test2),
    path('http_response/', http_response),
    path('post/', post_view),
    #path('product-detail', product_detail_view),
    path('redirect/', redirect_view),
    path('admin/', admin.site.urls),
    path('shop_admin/', shop_admin.urls),
    path('search_view/', search_view),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.index_title = 'Django Ecom 後台'
admin.site.site_header = 'CodeCroc 管理'
admin.site.site_title = 'CodeCroc Ecom'

shop/urls.py
from django.urls import path, reverse, reverse_lazy
from django.conf.urls import url
from django.views.generic.base import TemplateView, RedirectView

from .views import (ProductDetailView, product_detail_view,
                    product_list_view, ProductListView,)

app_name = 'shop'

urlpatterns = [
    #    path('product/<int:id>', product_detail_view, name='product-detail'),
    #path('products/', product_list_view, name='product-list'),
    url(r'^product/(?P<id>\d+)/$', product_detail_view, name='product-detail'),
    path('template-view', TemplateView.as_view(template_name='shop/template-view.html'),
         name='template-view'),
    path('redirect-view', RedirectView.as_view(url=reverse_lazy('shop:template-view')),
         name='redirect-view'),
    path('products/', ProductListView.as_view(), name='product-list'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product-detail')
]

shop/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.db.models import Sum, F
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.safestring import mark_safe

from uuid import uuid4

User = settings.AUTH_USER_MODEL  # auth.User


def path_and_rename(instance, filename):
    ext = filename.split('.')[-1]
    now = timezone.now()
    return f"{now.year}/{now.month}/{now.day}/{uuid4().hex}.{ext}"


class Category(models.Model):
    title = models.CharField('標題', max_length=63)
    image = models.ImageField(
        '圖片', null=True, default=None, upload_to=path_and_rename)
    created_at = models.DateTimeField('建立於', auto_now_add=True)
    updated_at = models.DateTimeField('更新於', auto_now=True)

    def __str__(self):
        return self.title

    def image_preview(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.image.url)) if self.image else '-'
    image_preview.short_description = '圖片預覽'

    def test_button(self):
        return mark_safe(f"<button>{self.title}</button>")

    class Meta:
        verbose_name = '產品類別'
        verbose_name_plural = '產品類別'


class Product(models.Model):
    title = models.CharField('標題', max_length=127)
    description = models.TextField('描述', blank=True, null=True)
    primary_image = models.ImageField(
        '主要圖片', null=True, default=None, upload_to=path_and_rename)
    original_price = models.DecimalField(
        '原價', max_digits=6, decimal_places=2, default=0.00)
    discounted_price = models.DecimalField(
        '特價', max_digits=6, decimal_places=2, default=0.00)
    category = models.ForeignKey(
        Category, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='產品類別')
    created_at = models.DateTimeField('建立於', auto_now_add=True)
    updated_at = models.DateTimeField('更新於', auto_now=True)

    def __str__(self):
        return self.title

    def image_preview(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.primary_image.url)) if self.primary_image else '-'
    image_preview.short_description = '圖片預覽'

    class Meta:
        verbose_name = '產品'
        verbose_name_plural = '產品'


class Order(models.Model):

    class StatusChoices(models.TextChoices):
        ORDER_SENT = 'order_sent', '已下單'
        PAID = 'paid', '已付款'
        INVOICE_MADE = 'invoce_made', '已開立發票'
        PRODUCT_SENT = 'product_sent', '已寄出'
        ORDER_CLOSED = 'order_closed', '訂單結束'
        ORDER_FAILED = 'order_failed', '訂單失敗'

    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='客戶')
    created_at = models.DateTimeField('建立於', auto_now_add=True)
    updated_at = models.DateTimeField('更新於', auto_now=True)
    total = models.DecimalField(
        '總價', max_digits=6, decimal_places=2, default=0.00)
    status = models.CharField(
        '訂單狀態', max_length=63, choices=StatusChoices.choices, default=StatusChoices.ORDER_SENT)
    products = models.ManyToManyField(
        Product, verbose_name='訂單內容', related_name='orders', through='Mapping')

    # TODO: remove blank, null = True
    name = models.CharField('姓名', max_length=15, blank=True, null=True)
    phone = models.CharField('電話', max_length=15, blank=True, null=True)
    address = models.CharField('地址', max_length=127, blank=True, null=True)

    note = models.TextField('備註', blank=True, null=True)

    def __str__(self):
        return f"{self.id}"

    class Meta:
        verbose_name = '訂單'
        verbose_name_plural = '訂單'


class Mapping(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, verbose_name='訂單')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='產品')
    quantity = models.PositiveIntegerField('數量', default=1)
    # subtotal = models.DecimalField(
    #    '小計', max_digits=6, decimal_places=2, default=0.00)

    def subtotal(self):
        return self.product.discounted_price * self.quantity
    subtotal.short_description = '小計'

    def __str__(self):
        return f"訂單編號：{self.order.id}-{self.product.title}"

    class Meta:
        verbose_name = '訂單產品'
        verbose_name_plural = '訂單產品'


@receiver(post_delete, sender=Mapping)
@receiver(post_save, sender=Mapping)
def update_order_total(sender, *args, **kwargs):
    instance = kwargs['instance']
    order = instance.order
    output = Mapping.objects.filter(order=order).aggregate(
        t=Sum(F('product__discounted_price')*F('quantity')))
    order.total = output['t'] if output['t'] is not None else 0.0
    order.save()

shop/views.py
from django.core import paginator
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.http.response import Http404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView

from shop.models import Product

# Create your views here.


def home(req):
    # return HttpResponse('<h1>Hello World</h1>')
    return render(req, template_name='test.html')


@login_required(login_url='/auth/login')
def test2(req):
    return render(req, template_name='shop/test2.html')


def http_response(req):
    return HttpResponse('<h1>From Http Response</h1>')


def redirect_view(req):
    return HttpResponseRedirect('/')


def post_view(req):
    if req.method == 'POST':
        data = req.POST
        mytext = data.get('mytext')
        print(mytext)
        print(req.META)
    return render(req, template_name='shop/test-form.html')


def product_detail_view(req, id):
    obj = get_object_or_404(Product, id=id)
    context = {'object': obj}
    template = 'shop/product-detail.html'

    return render(req, template, context)


def product_list_view(req):
    data = req.GET
    per_page = 6  # 每頁顯示多少個
    products = Product.objects.order_by('-updated_at')
    paginator = Paginator(products, per_page)
    try:
        page = int(data.get('p')) if data.get('p') else None
    except:
        raise Http404
    if page:
        try:
            products = paginator.page(page)
        except:
            raise Http404
    else:
        products = paginator.page(1)

    print(paginator.count)
    print(paginator.num_pages)
    print(paginator.page_range)

    context = {
        'products': products,
        'page_range': paginator.page_range
    }
    template = 'shop/product-list.html'

    return render(req, template, context)


class ProductListView(ListView):
    model = Product
    template_name = 'shop/product-list-generic.html'

    paginate_by = 6
    #queryset = Product.objects.filter(title='new product')

    # def get_queryset(self):
    #    return Product.objects.filter(title='new product')

    context_object_name = 'products'

    title = '商品列表'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.title
        return context


class ProductDetailMixin(object):
    title = None
    template_name = 'shop/product-detail-generic.html'

    def get_title(self):
        return self.title

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.get_title()
        return context


class ProductDetailView(LoginRequiredMixin, ProductDetailMixin, DetailView):
    login_url = '/auth/login/'

    title = 'Hello World'
    model = Product
    template_name = 'shop/product-detail-generic.html'

templates/shop/post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form action="." method="POST">
      {% csrf_token %}
      <input name="mytext" type="text" />
      <input type="submit" value="送出" />
    </form>
  </body>
</html>

templates/shop/product-detail-generic.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ object.title }}</title>
</head>
<body>
	<!--<h1>{{ object.title }}</h1>-->
	<h1>{{ title }}</h1>
	{% if object.primary_image %}
		<img src="{{ object.primary_image.url }}" alt="{{ object.title }}" width="200px" height="200px" />
	{% endif %}
	<p>{{ object.description }}</p>
	<hr />
	{% if user.is_authenticated %}
		<p>歡迎回來，{{ user.get_username }}</p>
	{% endif %}
</body>
</html>

templates/shop/product-detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
	<h1>
		{{ object.title }}
	</h1>
	{% if object.primary_image %}
		<img src="{{ object.primary_image.url}}" alt="{{ object.title }}" width="100px" height="100px">
	{% else %}
		<p> - </p>
	{% endif %}
	<p>原價： {{ object.original_price }}</p>
	<p>特價： {{ object.discounted_price }}</p>
  </body>
</html>

templates/shop/product-list-generic.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>商品列表</title>
</head>
<body>
	<h1>{{ title }}</h1>
	{% for p in products  %}
		<h2>{{ p.title }}</h2>
		{% if p.primary_image %}
			<img src="{{ p.primary_image.url }}" alt="{{ p.title }}" width="100px" height="100px" />
		{% endif %}
		{% if p.description %}
			<p>{{ p.description }}</p>
		{% endif %}
	{% endfor %}
	{% if page_obj.has_previous %}
		<a href="?page={{ page_obj.previous_page_number }}"> &laquo; </a>
	{% endif %}
	{% for i in page_obj.paginator.page_range  %}
	<a href="{% url 'shop:product-list' %}?page={{ i }}">
		{{ i }}
	</a>
	{% endfor %}
	{% if page_obj.has_next %}
		<a href="?page={{ page_obj.next_page_number }}"> &raquo; </a>
	{% endif %}
</body>
</html>

templates/shop/product-list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>商品列表</title>
</head>
<body>
{% for p in products  %}
	<div>
		<h2>{{ p.title }}</h2>
		{% if p.primary_image %}
			<img src="{{ p.primary_image.url }}" alt="{{ p.title }}" width="100px" height="100px" />
		{% endif %}
		{% if p.description %}
			<p>{{ p.description }}</p>
		{% endif %}
	</div>
{% endfor %}
{% for i in page_range  %}
	<a href="{% url 'shop:product-list' %}?p={{ i }}">
		<button>{{ i }}</button>
	</a>
{% endfor %}
</body>
</html>

templates/shop/template-view.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Template View</title>
  </head>
  <body>
    <h1>From Template View</h1>
  </body>
</html>

templates/shop/test-form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test Form</title>
  </head>
  <body>
    <form action="." method="POST">
      {% csrf_token %}
      <input name="mytext" type="text" />
      <input type="submit" value="送出" />
    </form>
  </body>
</html>

templates/shop/test2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>From custom template</h1>
  </body>
</html>